name: Node.js Build and Playwright Test on PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Root Dependencies
      run: npm install

    - name: Run Build
      run: npm run build

    - name: Setup Playwright
      uses: microsoft/playwright-github-action@v1
      with:
        browsers: all

    - name: Install Dependencies for Playwright Tests
      run: npm install
      working-directory: _project-herokuapp-components-tests

    - name: Run Playwright Tests
      run: npx playwright test
      working-directory: _project-herokuapp-components-tests
